version: "3.5"
volumes:
  datadb:
  pgdata:
  pgadmin:

services:
  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=data
      - MYSQL_USER=data
      - MYSQL_PASSWORD=secret
    volumes:
      - datadb:/var/lib/mysql
    ports:
      - 0.0.0.0:3306:3306
    networks:
      - dataenv
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 0.0.0.0:5432:5432
    networks:
      - dataenv
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - dataenv
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 0.0.0.0:9002:80
      - 0.0.0.0:10002:443
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=secret
  redis:
    image: redis:6-alpine
    ports:
      - 0.0.0.0:6379:6379
  
  adminer:
    image: adminer
    # restart: always
    ports:
      - 127.0.0.1:9080:8080
    networks:
      - dataenv
  myadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 127.0.0.1:9081:80
    environment:
      - PMA_HOST=mariadb
    networks:
      - dataenv
  

  
networks:
  dataenv: 
